package com.andersonhsieh.ratesup.model


import com.google.gson.annotations.SerializedName
import java.text.SimpleDateFormat
import java.time.LocalDate


data class CurrencyData(
     @SerializedName("USD")    val USD: Double,
 @SerializedName("JPY")    val JPY: Double,
 @SerializedName("CNY")    val CNY: Double,
 @SerializedName("CHF")    val CHF: Double,
 @SerializedName("CAD")    val CAD: Double,
 @SerializedName("MXN")    val MXN: Double,
 @SerializedName("INR")    val INR: Double,
 @SerializedName("BRL")    val BRL: Double,
 @SerializedName("RUB")    val RUB: Double,
 @SerializedName("KRW")    val KRW: Double,
 @SerializedName("IDR")    val IDR: Double,
 @SerializedName("TRY")    val TRY: Double,
 @SerializedName("SAR")    val SAR: Double,
 @SerializedName("SEK")    val SEK: Double,
 @SerializedName("NGN")    val NGN: Double,
 @SerializedName("PLN")    val PLN: Double,
 @SerializedName("ARS")    val ARS: Double,
 @SerializedName("NOK")    val NOK: Double,
 @SerializedName("TWD")    val TWD: Double,
 @SerializedName("IRR")    val IRR: Double,
 @SerializedName("AED")    val AED: Double,
 @SerializedName("COP")    val COP: Double,
 @SerializedName("THB")    val THB: Double,
 @SerializedName("ZAR")    val ZAR: Double,
 @SerializedName("DKK")    val DKK: Double,
 @SerializedName("MYR")    val MYR: Double,
 @SerializedName("SGD")    val SGD: Double,
 @SerializedName("ILS")    val ILS: Double,
 @SerializedName("HKD")    val HKD: Double,
 @SerializedName("EGP")    val EGP: Double,
 @SerializedName("PHP")    val PHP: Double,
 @SerializedName("CLP")    val CLP: Double,
 @SerializedName("PKR")    val PKR: Double,
 @SerializedName("IQD")    val IQD: Double,
 @SerializedName("DZD")    val DZD: Double,
 @SerializedName("KZT")    val KZT: Double,
 @SerializedName("QAR")    val QAR: Double,
 @SerializedName("CZK")    val CZK: Double,
 @SerializedName("PEN")    val PEN: Double,
 @SerializedName("RON")    val RON: Double,
 @SerializedName("VND")    val VND: Double,
 @SerializedName("BDT")    val BDT: Double,
 @SerializedName("HUF")    val HUF: Double,
 @SerializedName("UAH")    val UAH: Double,
 @SerializedName("AOA")    val AOA: Double,
 @SerializedName("MAD")    val MAD: Double,
 @SerializedName("OMR")    val OMR: Double,
 @SerializedName("CUC")    val CUC: Double,
 @SerializedName("BYR")    val BYR: Double,
 @SerializedName("AZN")    val AZN: Double,
 @SerializedName("LKR")    val LKR: Double,
 @SerializedName("SDG")    val SDG: Double,
 @SerializedName("SYP")    val SYP: Double,
 @SerializedName("MMK")    val MMK: Double,
 @SerializedName("DOP")    val DOP: Double,
 @SerializedName("UZS")    val UZS: Double,
 @SerializedName("KES")    val KES: Double,
 @SerializedName("GTQ")    val GTQ: Double,
 @SerializedName("URY")    val URY: Double,
 @SerializedName("HRV")    val HRV: Double,
 @SerializedName("MOP")    val MOP: Double,
 @SerializedName("ETB")    val ETB: Double,
 @SerializedName("CRC")    val CRC: Double,
 @SerializedName("TZS")    val TZS: Double,
 @SerializedName("TMT")    val TMT: Double,
 @SerializedName("TND")    val TND: Double,
 @SerializedName("PAB")    val PAB: Double,
 @SerializedName("LBP")    val LBP: Double,
 @SerializedName("RSD")    val RSD: Double,
 @SerializedName("LYD")    val LYD: Double,
 @SerializedName("GHS")    val GHS: Double,
 @SerializedName("YER")    val YER: Double,
 @SerializedName("BOB")    val BOB: Double,
 @SerializedName("BHD")    val BHD: Double,
 @SerializedName("CDF")    val CDF: Double,
 @SerializedName("PYG")    val PYG: Double,
 @SerializedName("UGX")    val UGX: Double,
 @SerializedName("SVC")    val SVC: Double,
 @SerializedName("TTD")    val TTD: Double,
 @SerializedName("AFN")    val AFN: Double,
 @SerializedName("NPR")    val NPR: Double,
 @SerializedName("HNL")    val HNL: Double,
 @SerializedName("BIH")    val BIH: Double,
 @SerializedName("BND")    val BND: Double,
 @SerializedName("ISK")    val ISK: Double,
 @SerializedName("KHR")    val KHR: Double,
 @SerializedName("GEL")    val GEL: Double,
 @SerializedName("MZN")    val MZN: Double,
 @SerializedName("BWP")    val BWP: Double,
 @SerializedName("PGK")    val PGK: Double,
 @SerializedName("JMD")    val JMD: Double,
 @SerializedName("XAF")    val XAF: Double,
 @SerializedName("NAD")    val NAD: Double,
 @SerializedName("ALL")    val ALL: Double,
 @SerializedName("SSP")    val SSP: Double,
 @SerializedName("MUR")    val MUR: Double,
 @SerializedName("MNT")    val MNT: Double,
 @SerializedName("NIO")    val NIO: Double,
 @SerializedName("LAK")    val LAK: Double,
 @SerializedName("MKD")    val MKD: Double,
 @SerializedName("AMD")    val AMD: Double,
 @SerializedName("MGA")    val MGA: Double,
 @SerializedName("XPF")    val XPF: Double,
 @SerializedName("TJS")    val TJS: Double,
 @SerializedName("HTG")    val HTG: Double,
 @SerializedName("BSD")    val BSD: Double,
 @SerializedName("MDL")    val MDL: Double,
 @SerializedName("RWF")    val RWF: Double,
 @SerializedName("KGS")    val KGS: Double,
 @SerializedName("GNF")    val GNF: Double,
 @SerializedName("SRD")    val SRD: Double,
 @SerializedName("SLL")    val SLL: Double,
 @SerializedName("XOF")    val XOF: Double,
 @SerializedName("MWK")    val MWK: Double,
 @SerializedName("FJD")    val FJD: Double,
 @SerializedName("ERN")    val ERN: Double,
 @SerializedName("SZL")    val SZL: Double,
 @SerializedName("GYD")    val GYD: Double,
 @SerializedName("BIF")    val BIF: Double,
 @SerializedName("KYD")    val KYD: Double,
 @SerializedName("MVR")    val MVR: Double,
 @SerializedName("LSL")    val LSL: Double,
 @SerializedName("LRD")    val LRD: Double,
 @SerializedName("CVE")    val CVE: Double,
 @SerializedName("DJF")    val DJF: Double,
 @SerializedName("SCR")    val SCR: Double,
 @SerializedName("SOS")    val SOS: Double,
 @SerializedName("GMD")    val GMD: Double,
 @SerializedName("KMF")    val KMF: Double,
 @SerializedName("STD")    val STD: Double,
 @SerializedName("XRP")    val XRP: Double,
 @SerializedName("AUD")    val AUD: Double,
 @SerializedName("BGN")    val BGN: Double,
 @SerializedName("BTC")    val BTC: Double,
 @SerializedName("JOD")    val JOD: Double,
 @SerializedName("GBP")    val GBP: Double,
 @SerializedName("ETH")    val ETH: Double,
 @SerializedName("EUR")    val EUR: Double,
 @SerializedName("LTC")    val LTC: Double,
 @SerializedName("NZD")    val NZD: Double,

){




}